version: "3"
services:
  mongo:
    container_name: mongo-vuttr
    image: mongo:4.4
    restart: always
    volumes:
      - ./data/:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-vuttr
    image: node:14
    working_dir: /usr/src/vuttr
    restart: always
    command: yarn debug
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/vuttr/dist/
      - ./node_modules/:/usr/src/vuttr/node_modules/
      - ./package.json:/usr/src/vuttr/package.json
    ports:
      - "3000:3000"
      - "9229:9229"
    links:
      - mongo